//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInventarioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<int> existencia { get; set; }
        public int id_categoria { get; set; }
        public string codigo { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_modelo { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string descripcion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
