//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInventarioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Operacion
    {
        public int id_Rol_Operacion { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<int> id_Operacion { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
